version: '3'
services:
  db:
    image: mariadb
    volumes:
      - "/var/lib/mysql"
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - overlay
  python:
    build:
      context: ./python
    depends_on:
      - db
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "8081:3000"
    networks:
      - overlay
    volumes:
      - "/var/lib/grafana"

networks:
  overlay:
